name: "Ship It!"

concurrency:
  # There should only be able one running job per repository / branch combo.
  # We do not want multiple deploys running in parallel.
  group: ${{ github.repository }}-${{ github.ref_name }}

on:
  push:
    branches:
      - 'master'
      - 'daggerize'
  workflow_dispatch:

jobs:
  dagger:
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout code..."
          uses: actions/checkout@v3

        - name: "Setup Go..."
          uses: actions/setup-go@v4
          with:
            go-version: "1.20"

        - name: "Ship it!"
          env:
            FLY_API_TOKEN: "${{ secrets.FLY_API_TOKEN }}"
            OP_SERVICE_ACCOUNT_TOKEN: "${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}"
          run: |
            go run . cicd --app "${{ vars.APP }}"
